Update in the driver eks update method that allows you to update the …
rancher/kontainer-engine pull request #231
Opened 2020-07-07 13:59 UTC by ribeiro-rodrigo

This functionality allows changing the number of nodes in the EKS cluster.

2020-11-25 01:38 UTC, rmweir requested changes
Can you change errors to be named err for consistency?

2020-11-25 01:38 UTC, rmweir commented on drivers/eks/eks_driver.go
> +	templateOutput, errGetTemplate := cloudFormationService.GetTemplate(&cloudformation.GetTemplateInput{
```suggestion
	templateOutput, err := cloudFormationService.GetTemplate(&cloudformation.GetTemplateInput{
```

2020-11-25 01:38 UTC, rmweir commented on drivers/eks/eks_driver.go
> +
remove new line

2020-11-25 01:38 UTC, rmweir commented on drivers/eks/eks_driver.go
> +	_, errUpdate := cloudFormationService.UpdateStack(updateInput)
```suggestion
	_, err := cloudFormationService.UpdateStack(updateInput)
```

2020-11-25 01:38 UTC, rmweir commented on drivers/eks/eks_driver.go
> +
remove newline

2020-11-25 01:38 UTC, rmweir commented on drivers/eks/eks_driver.go
> +	if newState.DesiredASGSize > 0 && newState.DesiredASGSize != state.DesiredASGSize {
Can you move the newState.DesiredASGSize to the validate() function and have validate work for updates and create or create a separate function?

2020-11-25 01:38 UTC, rmweir commented on drivers/eks/eks_driver.go
> +func (d *Driver) updateNodePoolAndAwait(state state, info *types.ClusterInfo) error {
I think the receiver can be removed
```suggestion
func updateNodePoolAndAwait(state state, info *types.ClusterInfo) error {
```

2020-12-22 07:10 UTC, deniseschannon commented
As we are moving to the new EKS v2 support in Rancher v2.5, we encourage all users to upgrade and use the new provisioner which allows being able to change the number of nodes in EKS.

2020-12-22 07:10 UTC, closed without merging